/** Presupuesto y control del gasto. */
export const PRESUPUESTO = [
  'Escribe tus gastos el mismo día. La memoria de lo que gastaste ayer ya está adulterada por lo que quieres creer.',
  'Antes de recortar, mide un mes completo. No puedes optimizar lo que todavía no sabes cuánto es.',
  'La regla 50/30/20 no es ley: es un punto de partida. Ajústala a tu arriendo real, no al de un libro estadounidense.',
  'Un presupuesto que te hace sentir culpable se abandona en tres semanas. Deja siempre una categoría de gusto sin justificar.',
  'Divide el arriendo entre 30 y verás lo que te cuesta cada día dormir donde duermes. Cambia cómo evalúas mudarte.',
  'Los gastos hormiga no son el café: son los que no recuerdas haber hecho. Búscalos en el extracto, no en la memoria.',
  'Revisa tu presupuesto el día que te pagan, no el último del mes. Decidir con el dinero en mano es distinto a lamentarlo después.',
  'Si una categoría se pasa tres meses seguidos, el presupuesto está mal, no tu comportamiento. Súbelo y recorta en otra.',
  'Pon el mercado y los domicilios en categorías separadas. Sumados esconden que uno cuesta el triple por la misma comida.',
  'Un gasto fijo que puedes cancelar en un clic no es fijo: es una decisión que renuevas cada mes sin darte cuenta.',
  'Antes de comprar algo de más de 300 mil, espera 72 horas. La mitad de las veces las ganas se van solas.',
  'Cuenta los días, no las semanas: "me quedan 11 días con 400 mil" decide mejor que "voy bien de plata".',
  'El presupuesto anual revela lo que el mensual esconde: la matrícula, el seguro, el impuesto del carro. Repártelos entre doce.',
  'Si compras con tarjeta para "llevar el control", revisa que no sea al revés: la tarjeta separa el dolor del gasto.',
  'Anota también los ingresos pequeños. Un presupuesto que solo mide salidas te hace sentir más pobre de lo que eres.',
  'La categoría "Otros" que crece sin parar es una señal: hay algo que no quieres nombrar.',
  'Presupuestar en efectivo lo que más se te va de las manos funciona porque el billete se acaba y la tarjeta no.',
  'Compara meses, no días. Un martes caro no dice nada; tres meses de martes caros sí.',
  'Antes de subir de plan en cualquier servicio, calcula el costo anual. Veinte mil al mes son 240 mil al año.',
  'Si tu presupuesto solo funciona cuando no pasa nada, no es un presupuesto: es un deseo.',
  'Revisa las suscripciones cada seis meses. Las que no recordabas que tenías son las que debes cancelar.',
  'El almuerzo fuera cinco días a la semana son unos 200 mil al mes. No lo cortes: negóciate llevarlo dos días.',
  'Un aumento de sueldo sin presupuesto nuevo se evapora en tres meses. Decide a qué va antes de que llegue.',
  'Si compartes gastos, escríbelos. La contabilidad mental entre dos personas siempre favorece a quien la lleva.',
  'Ponle nombre a cada peso antes de que empiece el mes. El dinero sin destino asignado se gasta solo.',
]

/** Ahorro y fondo de emergencia. */
export const AHORRO = [
  'Ahorra apenas te paguen, no con lo que sobre. Lo que sobra nunca sobra.',
  'Un fondo de emergencia de tres meses no es una meta de inversión: es el permiso para poder invertir tranquilo.',
  'Automatiza la transferencia al ahorro el día del pago. La fuerza de voluntad es un recurso agotable; la automatización no.',
  'Empieza por un fondo de un millón antes de pensar en seis meses de gastos. La primera meta debe ser alcanzable.',
  'Guarda el fondo de emergencia en una cuenta distinta a la del día a día. Verlo en el mismo saldo lo convierte en gasto.',
  'Si tu ahorro rinde menos que la inflación, estás perdiendo plata despacio. Que sea seguro no significa que sea gratis.',
  'Subir el ahorro un 1 % cada vez que te aumentan el sueldo no se siente, y en cinco años cambia tu vida.',
  'El mejor momento para ahorrar fue cuando ganabas menos y no lo hacías. El segundo mejor es esta quincena.',
  'Un bolsillo por meta funciona mejor que un solo saldo grande: cuesta más sacar del "viaje" que de "ahorros".',
  'Redondea cada gasto hacia arriba y guarda la diferencia. Es invisible y suma más de lo que crees.',
  'Ahorrar para algo concreto rinde más que ahorrar por ahorrar. El cerebro protege metas, no cifras.',
  'Si te cuesta ahorrar, no es falta de disciplina: es que el ahorro está compitiendo con el gasto en el mismo lugar.',
  'La prima o el bono no son plata extra: son el ahorro de un año que llegó de golpe.',
  'Guarda el equivalente al deducible de tu seguro. Es la emergencia más probable y la más olvidada.',
  'Antes de invertir un peso, ten con qué pagar dos meses sin ingresos. Invertir sin colchón te obliga a vender en el peor momento.',
  'Un ahorro que puedes retirar en un clic no es un fondo de emergencia: es una cuenta corriente con otro nombre.',
  'Si el ahorro te obliga a endeudarte a fin de mes, estás ahorrando de más. Baja el monto y hazlo sostenible.',
  'Nombra tus metas con lo que significan, no con la cifra. "Viaje con mi mamá" se protege mejor que "meta 12M".',
  'Guarda por adelantado los gastos anuales que ya sabes que vienen. Diciembre nunca es una sorpresa.',
  'El día que llegues a un mes de gastos ahorrado, celébralo. Los hitos sin celebrar se abandonan.',
]
