/** Mercados, divisas y activos alternativos. */
export const MERCADOS = [
  'El dólar sube y baja; tener parte del ahorro en otra moneda es cobertura, no especulación.',
  'Comprar dólares "porque va a subir" es especular. Comprarlos cada mes para diversificar es otra cosa.',
  'La tasa de cambio de tu app no es la del mercado: tiene un margen. Compárala antes de convertir montos grandes.',
  'Invertir en el exterior te expone a dos riesgos: el del activo y el de la moneda. Ambos pueden jugar a favor.',
  'Un ETF que replica un índice cobra mucho menos que un fondo que intenta ganarle. A largo plazo eso decide.',
  'La bolsa colombiana es pequeña y concentrada. Si inviertes solo local, revisa cuánto riesgo estás asumiendo.',
  'Los CDT ofrecen tasas mejores a plazos largos, pero encierran tu dinero. Escalona vencimientos para no quedarte sin liquidez.',
  'Un fondo de inversión colectiva con retiro inmediato paga menos que uno con permanencia. Estás pagando por la liquidez.',
  'Las cripto se mueven mucho más que la bolsa. Si tu porción te quita el sueño, es demasiado grande.',
  'Guardar cripto en un exchange es confiar en un tercero. Si el monto importa, aprende sobre custodia propia.',
  'El oro protege en crisis pero no genera flujo. Es seguro, no una máquina de rentabilidad.',
  'La finca raíz tiene costos que no se ven: predial, administración, vacancia, reparaciones. La rentabilidad bruta engaña.',
  'Un inmueble arrendado que renta menos del 0,5 % mensual del valor rinde menos que instrumentos más simples.',
  'La liquidez tiene valor: poder salir cuando quieras vale una parte de la rentabilidad que dejas de ganar.',
  'Si inviertes en dólares, decide de antemano si conviertes de vuelta a pesos o no. Improvisar eso destruye retorno.',
  'Los mercados caen rápido y suben lento. Esa asimetría es la que pone a prueba la paciencia.',
  'Nadie toca la campana cuando empieza una recuperación. Estar invertido es lo que la captura.',
  'Perderse los diez mejores días de una década reduce el retorno a la mitad. Y esos días suelen seguir a los peores.',
  'Los índices se recomponen solos: las empresas que fallan salen y entran otras. Por eso el índice sobrevive a sus empresas.',
  'Antes de invertir en algo exótico, pregúntate quién está al otro lado de la operación y por qué vende.',
]

/** Salud financiera y mentalidad de largo plazo. */
export const MENTALIDAD = [
  'La riqueza es lo que no ves: el carro que no compraste, la inversión que dejaste crecer.',
  'Ser rico es tener cosas; tener dinero es tener opciones. No son lo mismo y solo una da tranquilidad.',
  'Tu tasa de ahorro depende más de tu humildad que de tu ingreso.',
  'Lo que hagas los próximos diez años importa más que lo que hagas esta semana. Pero solo puedes empezar esta semana.',
  'El objetivo no es morir con la mayor cifra: es no tener que decir que no a lo que importa.',
  'Ahorrar sin meta también sirve: te compra flexibilidad, que es lo más caro del mercado.',
  'Los grandes saltos de patrimonio vienen de pocas decisiones. El resto es no arruinarlas.',
  'Evitar errores grandes rinde más que acertar jugadas brillantes.',
  'La paciencia es una ventaja competitiva porque casi nadie la tiene.',
  'Si tu plan requiere que el mercado se comporte de cierta forma, no es un plan: es una apuesta.',
  'La estabilidad emocional vale más que la inteligencia financiera. Quien no vende en pánico ya va ganando.',
  'Nadie piensa en tu dinero tanto como tú. Ni tu asesor, ni tu banco, ni tu familia.',
  'Compara tu vida de hoy con la de hace cinco años, no con la de alguien en redes.',
  'El dinero compra tiempo y tranquilidad. Si tu forma de ganarlo te quita ambas, revisa el intercambio.',
  'Una decisión financiera buena suele ser aburrida. Si te emociona, desconfía.',
  'Aprende a decir "no me alcanza" sin vergüenza. Es la frase que más patrimonio ha construido.',
  'Define tu suficiente antes de perseguir el más. Sin esa línea, el juego no termina nunca.',
  'La suerte y el riesgo son hermanos. Reconocer el papel de la suerte en tus aciertos te hace mejor decidiendo.',
  'El costo de la libertad financiera se paga en decisiones pequeñas y repetidas, no en un golpe de suerte.',
  'Empieza hoy con lo que tienes. El plan perfecto que empieza el mes que viene casi nunca empieza.',
]

/** Momentos del año y situaciones puntuales. */
export const MOMENTOS = [
  'En enero suben los precios y bajan las ganas de presupuestar. Aprovecha diciembre para dejarlo listo.',
  'La prima de diciembre no es para diciembre: es para el enero que viene después.',
  'Antes de un viaje, presupuesta un 20 % extra. Lo que se sale de cuenta nunca es el tiquete.',
  'Avisa al banco antes de viajar al exterior o te bloquearán la tarjeta en el peor momento.',
  'Pagar en pesos en el exterior con tarjeta suele salir más caro que pagar en la moneda local. Elige siempre la local.',
  'Antes de comprar en temporada de descuentos, haz la lista una semana antes. Comprar con lista previa filtra el impulso.',
  'La matrícula del semestre es predecible: divídela entre seis meses en lugar de sufrirla de golpe.',
  'Revisa el impuesto vehicular en los primeros meses del año, cuando hay descuento por pronto pago.',
  'Si te vas a mudar, calcula tres meses de gastos duplicados. Nunca sale limpio.',
  'Un cambio de trabajo con vacío entre contratos exige colchón. Cuenta las semanas sin ingreso antes de renunciar.',
  'Antes de aceptar una oferta, compara el paquete completo, no el salario: prestaciones, horario, transporte y estabilidad.',
  'Las fechas de corte de tus tarjetas definen cuánto tiempo tienes para pagar. Conócelas y compra justo después del corte.',
  'Si te llega un ingreso extraordinario, espera una semana antes de decidir. La euforia decide mal.',
  'Cada aumento de arriendo es el momento de recalcular si sigue teniendo sentido quedarte.',
  'En época de tasas altas, los CDT rinden bien y las deudas duelen más. Ajusta las dos cosas a la vez.',
  'Los seguros y suscripciones se renuevan solos. Pon un recordatorio un mes antes de cada renovación.',
  'Al cerrar el año, revisa qué metas cumpliste y cuáles no. Las que llevan dos años sin avanzar hay que cambiarlas o soltarlas.',
  'Antes de fin de año, revisa si te conviene hacer aportes voluntarios. En enero ya no aplica para ese año.',
  'Si vas a tener un hijo, empieza a vivir con el presupuesto nuevo antes de que llegue. Ahorras la diferencia y practicas.',
  'Los meses de cinco viernes desordenan el presupuesto de quien cobra semanal. Míralos en el calendario y prepáralos.',
  'El mejor día para revisar tus finanzas es el que ya está en tu calendario. Agéndalo ahora.',
  'Cuando algo salga mal con el dinero, escribe qué pasó. El registro de errores propios es el mejor curso de finanzas.',
  'Si llevas seis meses con el mismo plan y funciona, no lo cambies por aburrimiento.',
  'Cada peso que registres hoy es información que tu yo de dentro de un año va a agradecer.',
  'La constancia le gana al monto: 100 mil al mes durante diez años superan a un millón una sola vez.',
]
