/** Psicología del dinero y hábitos. */
export const PSICOLOGIA = [
  'Gastar para sentirte mejor funciona veinte minutos y se cobra el resto del mes.',
  'Compararte con quien gana el doble no te motiva: te hace tomar decisiones de alguien que no eres.',
  'Lo que llamas "me lo merezco" a veces es "estoy cansado". El descanso sale más barato que la compra.',
  'El dinero no cambia quién eres, amplifica lo que ya hacías. Si gastas de más ganando poco, ganarás más y gastarás más.',
  'Las finanzas no son un examen de inteligencia: son un examen de constancia.',
  'Un mes malo no borra un año bueno. No abandones el sistema por un tropiezo.',
  'Habla de plata con tu pareja antes de que sea un problema. El silencio se convierte en resentimiento.',
  'Si algo te da vergüenza registrar, regístralo igual. Los datos que ocultas son justo los que necesitas ver.',
  'La inflación del estilo de vida es silenciosa: subes de sueldo y de gastos a la vez, y sigues igual de justo.',
  'Nadie está mirando tu carro tanto como crees. La mayoría de las compras de estatus se hacen para una audiencia que no existe.',
  'El "es solo esta vez" repetido cuatro veces al mes es un gasto fijo.',
  'Ver tu patrimonio subir es adictivo en el buen sentido. Míralo una vez al mes, no cinco veces al día.',
  'Los descuentos no ahorran plata: la gastan más barato. Solo ahorras si ibas a comprarlo de todas formas.',
  'Ponerle fricción a lo que gastas de más funciona: borra la tarjeta guardada en las apps de compras.',
  'La libertad financiera no es tener mucho: es que una mala noticia no te cambie los planes.',
  'Decidir cuando estás cansado, con hambre o molesto sale caro. Aplaza la compra, no la decisión de aplazar.',
  'Escribe qué significa "suficiente" para ti. Sin esa línea, ninguna cifra la alcanza.',
  'Tu yo de dentro de diez años no puede opinar hoy. Ahorra por él, porque no tiene voz en esta conversación.',
  'Contar la plata que tienes tranquiliza más que ganar más. El desorden pesa más que la cantidad.',
  'Empieza por lo aburrido: fondo de emergencia, deudas caras, gastos fijos. Lo emocionante viene después y rinde menos.',
]

/** Ingresos, trabajo y contexto colombiano. */
export const INGRESOS = [
  'Negociar el sueldo una vez rinde más que ahorrar un año. Es la inversión con mayor retorno por hora dedicada.',
  'Un ingreso extra vale doble si va entero al ahorro: no cambia tu estilo de vida y acelera tus metas.',
  'Antes de aceptar un aumento en especie, calcula cuánto vale en plata. Un beneficio que no usas vale cero.',
  'Si eres independiente, sepárate un sueldo fijo y deja el resto en la cuenta del negocio. Mezclarlos oculta si estás ganando.',
  'Como independiente, aparta desde el primer peso lo de la retención y la seguridad social. Ese dinero nunca fue tuyo.',
  'La prima de junio y diciembre es previsible: decide en enero a qué va, no en la semana que llega.',
  'Las cesantías rinden más donde están que gastadas: solo úsalas para vivienda o educación, que es para lo que existen.',
  'Revisa tu aporte a pensión obligatoria y qué fondo lo maneja. Es la inversión más grande de tu vida y casi nadie la mira.',
  'Los aportes voluntarios a pensión o AFC bajan la base de retención. Consulta si te conviene antes de diciembre, no en abril.',
  'Si te acercas al tope de declarar renta, guarda soportes durante el año. Buscarlos después cuesta más que archivarlos.',
  'El 4x1000 se te va sin que lo veas. Marca una cuenta como exenta: es un trámite de cinco minutos al año.',
  'Un segundo ingreso te da poder de negociación en el primero, aunque nunca lo uses.',
  'Cobra por adelantado o por hitos si trabajas por proyectos. El flujo de caja mata más negocios que la falta de clientes.',
  'Sube tus tarifas al menos con la inflación. No hacerlo es bajarlas cada año en silencio.',
  'Ten claro cuánto vale tu hora. Sin eso no puedes decidir qué delegar ni qué rechazar.',
  'Un cliente que te paga tarde cuesta más que uno que paga menos. Cóbrale la demora o suéltalo.',
  'Si trabajas por prestación de servicios, tu ingreso real es lo que queda después de salud, pensión y ARL. Compara con eso, no con el bruto.',
  'Guarda tres meses de gastos si eres independiente, y seis si tus ingresos son estacionales.',
  'Formaliza los acuerdos por escrito aunque sea con conocidos. El correo de confirmación ya es un contrato.',
  'Reinvierte en lo que aumenta tu capacidad de ganar, no en lo que la aparenta.',
]

/** Compras grandes, vivienda y vehículo. */
export const COMPRAS = [
  'Antes de comprar carro, suma seguro, impuesto, parqueadero, mantenimiento y gasolina. El precio del carro es la parte pequeña.',
  'Un carro pierde buena parte de su valor en los primeros años. Comprar de dos o tres años te ahorra esa caída.',
  'La cuota inicial de vivienda no es el único costo: escrituras, notaría, beneficencia y registro suman varios millones más.',
  'Comparar arriendo contra cuota de crédito ignora el predial, la administración y el mantenimiento. Súmalos antes de decidir.',
  'Si vas a pedir crédito hipotecario, simula la cuota con una tasa dos puntos más alta. Que aguante también en el mal escenario.',
  'Abonar a capital reduce plazo o cuota. Pide siempre que sea a capital, no a intereses futuros.',
  'Comprar por metro cuadrado barato en zona sin transporte es caro: lo pagas en horas de vida.',
  'Antes de una compra grande, revisa si la vas a usar más de veinte veces. Si no, alquilarla sale mejor.',
  'La garantía extendida rara vez compensa. Guarda ese dinero: cubrirá varias reparaciones y te quedará saldo.',
  'Negocia el precio final, no la cuota mensual. Quien te vende sabe que mirando la cuota pagas más.',
  'Si el electrodoméstico consume mucho, el precio de compra no es el costo real. Mira el consumo antes que la etiqueta.',
  'Un imprevisto de vivienda ocurre cada año: separa un porcentaje mensual para reparaciones, no esperes a que pase.',
  'Comprar en cuotas algo que se deprecia más rápido de lo que lo pagas es perder dos veces.',
  'Antes de mudarte por un arriendo más barato, calcula el trasteo, el depósito y el transporte nuevo. A veces no compensa.',
  'La mejor negociación de una compra grande es estar dispuesto a no comprarla.',
]
