/** Deuda y tarjetas de crédito. */
export const DEUDA = [
  'Paga siempre el total de la tarjeta, no el mínimo. El mínimo está diseñado para que la deuda no se acabe nunca.',
  'La tasa de una tarjeta en Colombia ronda el 25-30 % efectivo anual. Ninguna inversión segura le gana; pagarla es la mejor rentabilidad que vas a encontrar.',
  'Diferir a cuotas no es gratis aunque diga "sin intereses": el precio suele venir ya cargado.',
  'Usa menos del 30 % de tu cupo. Por encima de eso el historial crediticio empieza a leerse como riesgo.',
  'Ataca primero la deuda de tasa más alta. La bola de nieve motiva, pero la avalancha te sale más barata.',
  'Si vas a diferir, que sea a la menor cantidad de cuotas que puedas pagar sin apretarte.',
  'Una tarjeta usada solo por el cashback y pagada completa cada mes es una herramienta. Usada para llegar a fin de mes es una trampa.',
  'Antes de pedir un préstamo, calcula cuánto vas a pagar en total, no la cuota. La cuota baja alarga el dolor.',
  'Consolidar deudas solo sirve si de verdad bajas la tasa y no vuelves a usar los cupos liberados.',
  'El avance en efectivo de la tarjeta cobra intereses desde el primer día, sin período de gracia. Es la forma más cara de conseguir plata.',
  'Cancela las tarjetas que no usas solo si no son las más antiguas: la antigüedad ayuda a tu historial.',
  'Si te ofrecen aumentar el cupo, acéptalo pero no lo uses: baja tu porcentaje de utilización sin costo.',
  'Pagar la tarjeta antes de la fecha de corte, no de la de pago, reduce el saldo que se reporta a las centrales.',
  'Una deuda con un familiar también es una deuda. Escríbela y ponle plazo, o se cobra en la relación.',
  'Si estás pagando intereses y ahorrando al mismo tiempo, revisa las tasas. Casi siempre gana pagar primero.',
  'El "compre ahora, pague después" es crédito con otro nombre. Súmalo a tus deudas cuando cuentes.',
  'Antes de refinanciar, pregunta cuánto llevas pagado de capital. A veces ya casi terminaste y refinanciar reinicia el reloj.',
  'Una cuota que supera el 30 % de tu ingreso te deja sin margen ante cualquier imprevisto.',
  'Revisa tu reporte en las centrales de riesgo una vez al año. Los errores existen y corregirlos es gratis.',
  'Si no puedes pagar, llama al banco antes de dejar de pagar. Negociar desde el día uno es distinto a negociar desde la mora.',
]

/** Inversión: fundamentos. */
export const INVERSION = [
  'El interés compuesto necesita tiempo, no genialidad. Empezar cinco años antes vale más que acertar el momento.',
  'Nadie puede predecir el mercado de forma consistente. Quien te dice que sí, te está vendiendo algo.',
  'Diversificar no es tener muchas cosas: es tener cosas que no caen a la vez.',
  'Un ETF de índice global te da miles de empresas por una comisión mínima. Es lo más cerca de "invierte y olvídate" que existe.',
  'Las comisiones se ven pequeñas y se comen décadas. Un 2 % anual se lleva casi la mitad de tu retorno en 30 años.',
  'Invertir la misma cantidad cada mes te evita la peor decisión: meterlo todo justo antes de una caída.',
  'Si no entiendes cómo gana dinero algo, no es una inversión: es una apuesta con vocabulario técnico.',
  'La rentabilidad pasada no predice la futura. Aparece en letra pequeña porque es cierto.',
  'Antes de invertir, define cuándo vas a necesitar esa plata. El plazo decide el instrumento, no al revés.',
  'Lo que no puedes permitirte perder no va a renta variable. Ni aunque la oportunidad parezca única.',
  'Rebalancear una vez al año es suficiente. Tocar el portafolio cada semana es cambiar estrategia por ansiedad.',
  'Una caída del 20 % es normal, ocurre cada pocos años. Si eso te quita el sueño, tu portafolio es más agresivo de lo que aguantas.',
  'El mayor enemigo de tu rentabilidad no es el mercado: es vender cuando cae y comprar cuando ya subió.',
  'Los dividendos reinvertidos son la mitad del retorno histórico de la bolsa. Cobrarlos y gastarlos cambia el resultado.',
  'Invertir en dólares desde Colombia añade el riesgo de la tasa de cambio, en los dos sentidos. Puede jugar a favor o en contra.',
  'Un CDT te asegura la tasa, no el poder adquisitivo. Compárala siempre contra la inflación esperada, no contra cero.',
  'No inviertas por FOMO. Si te enteraste por redes, ya vas tarde.',
  'Concentrar todo en la empresa donde trabajas duplica tu riesgo: si le va mal, pierdes el empleo y los ahorros el mismo día.',
  'El costo promedio de compra importa más que el precio de hoy. Anota siempre a cuánto compraste.',
  'Vender para "esperar a que baje" es intentar acertar dos veces seguidas. Casi nadie lo logra.',
  'Una acción que cayó 50 % necesita subir 100 % para volver a donde estaba. Por eso importa no perder mucho.',
  'Si tu horizonte es de más de diez años, las caídas son oportunidades de compra, no motivos de pánico.',
  'Revisa cuánto de tu portafolio está en un solo activo. Más del 20 % en uno solo ya no es diversificación.',
  'Las cripto pueden ser parte de un portafolio, pero dimensiónalas: lo que puedes perder entero sin cambiar tus planes.',
  'Antes de comprar, escribe por qué compras y a qué precio venderías. Leerlo en una caída vale más que cualquier análisis.',
]
