/** Herramientas, orden y método. */
export const METODO = [
  'Un sistema aburrido que sigues gana a uno brillante que abandonas en marzo.',
  'Revisa tus cuentas el mismo día cada semana. La regularidad importa más que la profundidad.',
  'Cierra el mes: cuánto entró, cuánto salió, cuánto quedó. Diez minutos que valen por horas de intuición.',
  'Ten menos cuentas de las que crees necesitar. Cada una es un lugar más donde perder de vista tu dinero.',
  'Nombra tus cuentas por su función, no por el banco: "gastos del mes" dice más que "ahorros 4321".',
  'Separa el dinero que ya tiene dueño del que está disponible. Ver un saldo alto que en realidad está comprometido lleva a gastarlo.',
  'Automatiza lo repetitivo: ahorro, pagos fijos, aportes. Reserva tu atención para las decisiones.',
  'Anota el porqué de los gastos grandes. En seis meses no vas a recordarlo y querrás saber si valió la pena.',
  'Un solo lugar donde ver todo vale más que cinco apps con información parcial.',
  'Si registrar te toma más de treinta segundos, vas a dejar de hacerlo. Optimiza el registro, no el análisis.',
  'Guarda una foto de los recibos importantes. La garantía la pide quien no la tiene.',
  'Ponle fecha a tus decisiones financieras: "reviso esto en tres meses" evita cambiar de opinión cada semana.',
  'Escribe tus reglas cuando estés tranquilo, para poder seguirlas cuando no lo estés.',
  'Compara tu patrimonio contigo mismo hace un año, no con nadie más. Es la única comparación útil.',
  'Haz una copia de seguridad de tus datos financieros. Perder tres años de historial duele más de lo que parece.',
  'Marca los gastos que fueron un error. Ver el patrón es más útil que lamentar cada uno.',
  'Ten una lista de deseos con fecha. Muchas cosas se caen solas si esperan un mes escritas.',
  'Registra también lo que ganas fuera del salario. Los ingresos irregulares son los que peor se controlan.',
  'Si una categoría no te dice nada al revisarla, fusiónala. Demasiado detalle es tan inútil como ninguno.',
  'Cierra el año con un balance completo. Es el momento de ver si el sistema funcionó, no de improvisar en enero.',
]

/** Consumo diario y ahorro concreto. */
export const CONSUMO = [
  'Haz mercado con lista y comido. Las dos cosas juntas bajan la cuenta más que cualquier cupón.',
  'Compara el precio por unidad, no por empaque. El tamaño grande no siempre sale más barato.',
  'Cocinar el domingo lo de tres días es la forma más aburrida y efectiva de bajar el gasto en comida.',
  'Un domicilio suma envío, propina y sobreprecio del plato. Suele costar el doble que la misma comida en el local.',
  'Revisa el plan de datos y de internet una vez al año. Las promociones nuevas casi nunca se aplican solas.',
  'Cancela y vuelve a suscribirte a los servicios que usas por temporadas. Nadie usa todo todo el año.',
  'Comparte planes familiares de streaming y música. El precio por persona cae a una fracción.',
  'Antes de reemplazar algo, pregunta si se puede reparar. Muchas veces cuesta la décima parte.',
  'Compra fuera de temporada lo que sabes que vas a necesitar. Los precios de la ropa siguen un calendario predecible.',
  'Los programas de puntos rinden si ya ibas a comprar. No compres para acumular puntos.',
  'Llevar botella de agua y café de casa parece trivial y son varios cientos de miles al año.',
  'Pon un tope mensual para salidas y respétalo. Es mejor decidir cuánto que decir que no a cada plan.',
  'Los gastos de transporte se optimizan mejor cambiando rutinas que cambiando de app.',
  'Antes de renovar el celular, pregúntate qué no puedes hacer con el actual. Casi siempre la respuesta es nada.',
  'Comprar calidad en lo que usas a diario y barato en lo que usas poco es la mejor regla de consumo que existe.',
  'Los precios terminados en 900 están diseñados para que leas el primer dígito. Redondea mentalmente hacia arriba.',
  'Si algo está en promoción y no lo necesitabas, no ahorraste nada: gastaste con descuento.',
  'Lleva el mercado a un monto fijo semanal. El límite obliga a priorizar sin llevar cuentas.',
  'Revisa los cobros automáticos de tu tarjeta cada trimestre. Ahí viven las suscripciones olvidadas.',
  'El gasto que más se puede reducir sin dolor es el que haces por costumbre, no por gusto.',
]

/** Emprendimiento y negocio propio. */
export const NEGOCIO = [
  'Separa las cuentas del negocio y las personales desde el primer día. Después es un desastre de desenredar.',
  'Un negocio rentable puede quebrar por flujo de caja. Vigila cuándo entra la plata, no solo cuánta.',
  'Págate un sueldo aunque sea pequeño. Si el negocio no lo soporta, ya sabes algo importante.',
  'Calcula tu punto de equilibrio: cuánto necesitas vender para no perder. Sin ese número navegas a ciegas.',
  'El precio bajo atrae al cliente que más trabajo da y menos paga. Subir precios filtra mejor que cualquier proceso.',
  'No reinviertas todo. Un negocio sin reservas muere en el primer mes malo.',
  'Los costos fijos son el riesgo: cuanto más bajos, más aguantas una mala racha.',
  'Antes de contratar, calcula el costo total con prestaciones. El salario es cerca del 60 % del costo real.',
  'Cobra un anticipo. Filtra a los clientes que no iban a pagar y financia el trabajo.',
  'Si un cliente representa más del 30 % de tus ingresos, no es un cliente: es tu jefe.',
  'Mide el margen por producto, no solo la venta total. Lo que más vendes puede ser lo que menos deja.',
  'Registra los gastos del negocio en el momento. Reconstruirlos en marzo cuesta más que la contabilidad.',
  'Invierte primero en lo que te quita tiempo, no en lo que se ve bien.',
  'Un negocio que solo funciona contigo presente es un empleo con más riesgo.',
  'Ten claro cuánto te cuesta conseguir un cliente. Si es más de lo que deja, estás pagando por vender.',
]
