/** Errores frecuentes y señales de alerta. */
export const ERRORES = [
  'Si una inversión promete rentabilidad fija y alta sin riesgo, es una estafa. No hay excepciones.',
  'Los esquemas que pagan con el dinero de los que entran después siempre colapsan. La pregunta no es si, sino cuándo.',
  'Nadie que de verdad gane dinero invirtiendo necesita cobrarte por enseñarte a hacerlo.',
  'Desconfía de la urgencia. "Solo por hoy" es la herramienta favorita de quien te quiere vender mal.',
  'Si no puedes explicarle a alguien en qué invertiste en dos frases, no lo entendiste.',
  'Los grupos de señales de trading ganan con la suscripción, no con las señales.',
  'Un asesor que cobra comisión por el producto que te vende tiene un conflicto de interés. Pregúntale cómo gana.',
  'Retirar de una inversión de largo plazo para una emergencia es la señal de que faltaba el fondo de emergencia.',
  'Prestarle a un amigo lo que no puedes perder arriesga dos cosas. Presta solo lo que regalarías.',
  'Firmar como codeudor es asumir la deuda entera, no la mitad. Si no la pagarías tú, no firmes.',
  'Poner todo el ahorro en el negocio propio es concentrar el riesgo al máximo. Deja siempre un colchón fuera.',
  'Comprar porque "está barato" sin saber cuánto vale no es invertir: es adivinar.',
  'Los rendimientos publicados en redes son los buenos. Nadie publica el mes que perdió.',
  'Un banco no te llama para pedirte claves ni códigos. Cuelga y llama tú al número de la tarjeta.',
  'Revisa el extracto completo, no solo el saldo. Los cobros pequeños y recurrentes se esconden ahí.',
  'Si te ofrecen "duplicar" tu dinero en semanas, el único que duplica es quien lo propone.',
  'No inviertas por lealtad a una marca. Que te guste el producto no dice nada del precio de la acción.',
  'Mover la plata cada vez que aparece algo mejor cuesta comisiones e impuestos que nadie suma.',
  'La deuda que se paga con más deuda no se está pagando: se está aplazando y creciendo.',
  'Si tu plan depende de que todo salga bien, no es un plan.',
]

/** Números y matemáticas del dinero. */
export const NUMEROS = [
  'Regla del 72: divide 72 entre la tasa anual y sabrás en cuántos años se duplica tu dinero.',
  'Un 10 % anual duplica el capital en poco más de siete años. Un 5 %, en catorce. El doble de tasa, la mitad del tiempo.',
  'Una tasa mensual del 2 % no es 24 % anual: es cerca del 27 % efectivo. El interés compuesto también trabaja en contra.',
  'Para pasar de efectiva anual a mensual no dividas entre doce: usa la raíz doceava. Dividir sobreestima el rendimiento.',
  'Un descuento del 50 % seguido de otro del 50 % no es 100 %: es 75 %. Los porcentajes no se suman.',
  'Si algo sube 50 % y luego baja 50 %, quedas por debajo de donde empezaste. Los porcentajes no son simétricos.',
  'La inflación del 5 % anual reduce el poder de compra de tu dinero a la mitad en catorce años.',
  'Una rentabilidad nominal del 8 % con inflación del 6 % es una rentabilidad real del 2 %. Solo la real cuenta.',
  'Comparar tasas exige la misma base: efectiva anual contra efectiva anual. Nominal y efectiva no son lo mismo.',
  'El costo de oportunidad es real: los 5 millones del carro nuevo son los 5 millones que no están rindiendo.',
  'Una comisión del 1,5 % anual parece nada y se lleva cerca del 30 % de tu retorno en 25 años.',
  'Calcula tu tasa de ahorro: ahorro dividido entre ingreso. Es el número que más predice tu futuro financiero.',
  'Si ahorras el 10 % de lo que ganas, necesitas nueve años de trabajo por cada año de libertad. Al 50 %, uno por uno.',
  'El valor presente de un ingreso futuro siempre es menor. Por eso "te pago en un año" nunca vale lo mismo.',
  'Cuando te ofrezcan cuotas, calcula el total pagado y réstale el precio de contado. Esa diferencia es el interés real.',
  'Un gasto diario de 15 mil son 5,4 millones al año. Los gastos pequeños se juzgan en escala anual.',
  'Para saber cuánto necesitas para vivir de rentas, multiplica tu gasto anual por 25. Es una aproximación conservadora.',
  'El promedio esconde los extremos. Mira también el peor mes, no solo el típico.',
  'Redondear siempre hacia arriba al presupuestar y hacia abajo al proyectar ingresos te deja margen en vez de sorpresas.',
  'Si el número no te cuadra, casi nunca es la calculadora: es una suposición que no escribiste.',
]

/** Familia, pareja y decisiones compartidas. */
export const FAMILIA = [
  'Hablen de dinero antes de vivir juntos. Descubrir las diferencias con las cuentas mezcladas es más caro.',
  'Tres cuentas funcionan bien en pareja: la tuya, la suya y la común. Autonomía sin dejar de construir juntos.',
  'Aporten a lo común en proporción al ingreso, no por mitades, si ganan distinto. Es más justo y dura más.',
  'Ponle cifra a los gastos de un hijo antes de tenerlo. La sorpresa no es el monto: es la frecuencia.',
  'Enseñar a los niños con una mesada pequeña y decisiones reales vale más que cualquier explicación.',
  'Un fondo para la educación de los hijos empezado al nacer necesita aportes mucho menores que uno empezado a los diez.',
  'Ayudar a la familia está bien; hacerlo sin límite te convierte en su fondo de emergencia. Define cuánto y con qué frecuencia.',
  'Deja por escrito dónde está todo: cuentas, claves, seguros. Un accidente no debería sumar un rompecabezas.',
  'Un testamento no es solo para gente con mucho patrimonio: es para que tu familia no pelee.',
  'Si prestas dinero a un familiar, decide de antemano qué pasa si no te paga. Esa conversación es más barata antes.',
  'Revisen juntos el presupuesto una vez al mes, veinte minutos. Evita las discusiones grandes.',
  'Las metas compartidas necesitan una cifra y una fecha, o cada uno imagina algo distinto.',
  'Comprar vivienda en pareja sin acuerdo escrito sobre los aportes genera conflictos si la relación cambia.',
  'No uses el dinero como herramienta de poder en la relación. Se paga con intereses en otra moneda.',
  'Si alguien de la casa lleva las cuentas solo, el otro queda vulnerable. Que ambos sepan dónde está todo.',
]
